# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171111_0657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submitted',
            new_name='Submission',
        ),
    ]
