# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_submission_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Year'),
        ),
    ]
