# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180218_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(),
        ),
    ]
