# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180220_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=3),
        ),
    ]
