# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
