# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20180316_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='down_votes',
        ),
        migrations.AddField(
            model_name='solution',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='solution',
            name='up_votes',
            field=models.ManyToManyField(related_name='up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
