# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180316_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='correct',
        ),
        migrations.AlterField(
            model_name='solution',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
