# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer',
            field=models.TextField(default='answer'),
        ),
    ]
