# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_puzzle_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
