# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_auto_20171111_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='trials',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='end_date',
            field=models.DateTimeField(default=puzzles.models.Puzzle.one_week_future, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
