# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_auto_20171123_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='correct_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='incorrect_points',
            field=models.IntegerField(default=3),
        ),
    ]
