# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 12:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_auto_20171123_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='correct_points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='incorrect_points',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
