# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_auto_20171228_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='subject',
        ),
    ]
