# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0010_auto_20180215_0506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
