# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 05:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20180215_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='correct_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='incorrect_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
