# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0014_auto_20180215_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='correct_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='incorrect_points',
            field=models.IntegerField(),
        ),
    ]
