# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0015_auto_20180215_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.Subject'),
        ),
    ]
