# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0017_auto_20180215_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
